CTAKES-148 java.io.FileNotFoundException: C:\cTAKES\xxxx\desc\Constituency Parser\desc\ConstituencyParserAnnotator.xml
And also 
java.io.FileNotFoundException: C:\cTAKES\xxxxxx\ctakes-coreference\desc\type-system\CorefTypes.xml
and also change an import I noticed that was referring to DocumentID.xml by relative path instead of using type-system.TypeSystem by name

git-svn-id: https://svn.apache.org/repos/asf/incubator/ctakes/branches/ctakes-3.0.0-incubating@1443039 13f79535-47bb-0310-9956-ffa450edef68