CTAKES-272) regression test run during build of 3.1.1 fails - this time with NoClassDefFoundError: org/mitre/medfacts/i2b2/api/AssertionDecoderConfiguration
git-svn-id: https://svn.apache.org/repos/asf/ctakes/branches/ctakes-3.1.1@1545812 13f79535-47bb-0310-9956-ffa450edef68